### PR TITLE
working

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by christopher-paul-shaw** [comment]
logs expired

**Comment by OskarStark** [comment]
What do you mean? 🧐

**Comment by devnix** [comment]
@OskarStark He means this:

image

**Comment by OskarStark** [comment]
Thank you, I updated this PR

**Comment by devnix** [comment]
If you want to leave this working unattended, you could run a [scheduled event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events)

**Comment by OskarStark** [comment]
Nice idea, open for a PR? 😄

**Comment by staabm** [comment]
Logs expired

**Comment by dillingham** [comment]
Logs expired

**Pull request closed without merging**
